sudo: false
dist: trusty

language: ruby

cache: bundler

notifications:
  email: false

rvm:
  - 2.6.5
  - 2.7.2

before_install:
  - gem install bundler

script:
  - bundle exec rspec --format progress
